### ISSUE TITLE
Bot online only when it's runned.

### ISSUE THREAD

**Issue by MitkoVtori** [Tree-Branchers/discord.py-quartz#3]
The bot Is online only while the code is running on computer.

Find a way to self host it and/or make the code run from internet.

#### Have an idea of how to fix this issue? Contact @MitkoVtori  - mitko.vtori@gmail.com

**Comment by RedTTG** [comment]
Мога на моя сървър

**Comment by MitkoVtori** [comment]
@JustRedTTG Можеш да накараш Бота да е постоянно активен?

**Comment by RedTTG** [comment]
> @JustRedTTG Можеш да накараш Бота да е постоянно активен?

Защо не

**Comment by MitkoVtori** [comment]
> > @JustRedTTG Можеш да накараш Бота да е постоянно активен?
> 
> Защо не

Окей, ще оставя issue-то отворено докато го направим, за всеки случай, ако не стане. (За сега няма да го хостваме, тъй като не работи, нито пък е готов.)

**Comment by MitkoVtori** [comment]
Bot hosted on our server!
